var listOfPlaces = ["Paris","Italy","Dubai","Machu Picchu","Maldives"];
console.log("Original order: ",listOfPlaces);
console.log("Alphabetical order: ",[...listOfPlaces].sort());
console.log("Original order: ",listOfPlaces);
console.log("Reverse alphabetical order: ",[...listOfPlaces].sort().reverse());
console.log("Original order: ",listOfPlaces);
console.log("Reverse order: ",listOfPlaces.reverse());
console.log("Original order: ",listOfPlaces);
console.log("Reverse order: ",listOfPlaces.reverse());
console.log("Original order: ",listOfPlaces);
console.log("Sort order: ",listOfPlaces.sort());
console.log("Original order: ",listOfPlaces);
console.log("Sort order: ",listOfPlaces.sort().reverse());
console.log("Original order: ",listOfPlaces);
